### ISSUE TITLE
Could you add a how to run it, please?

### ISSUE THREAD

**Issue by ldidry** [lamby/try.diffoscope.org#1]
Hello,

Would it be possible to have some documentation on how install and run this software please? I don't know a thing about Django or how to create a debian package.

Thank you.

**Comment by lamby** [comment]
Hi, take a look at the `.travis.yml` file - that should show you exactly what is run to create the package :)

**Comment by lamby** [comment]
Moved to https://salsa.debian.org/reproducible-builds/try.diffoscope.org/issues/1
